### ISSUE TITLE
Update Woocommerce plugins

### ISSUE THREAD

**Issue by gtenaschuk** [DinkumInteractive/mwu#35]
Would be good if we can see a way to update woocommerce plugins.
As they are not in the WP repository they are not being updated.
Maybe they could be updated after WP plugins and not deployed automatically... not sure if this wouldn't be tedious.... Good to think what is the best option.

**Comment by mustela** [comment]
Are they pro plugins? where are they? which are they ? if you can provide more info that would help.

**Comment by gtenaschuk** [comment]
Are they pro plugins? 
Not sure if all of them are PRO but they are allocated in woocommerce site
where are they? which are they?
You can see them in any site in the "Status Page -> Active Plugins" section
For example some of them in PCMS are 
WooCommerce Cart Reports	 	by WPBackOffice – 1.1.9 – 1.1.13 is available
WooCommerce Braintree Gateway	 	by WooThemes / SkyVerge – 3.3.1 – 3.3.2 is available

https://www.pcmsconcerts.org/wp-admin/admin.php?page=wc-status

**Comment by gtenaschuk** [comment]
Are they pro plugins?
Not sure if all of them are PRO but they are allocated in woocommerce site.

where are they? which are they ?
You can see them in any site in "Woocommerce Status" page "Active Plugins" section.
For example 

> WooCommerce Subscribe to Newsletter	 	by WooThemes – 2.3.3 – 2.3.5 is available

**Comment by mustela** [comment]
@gtenaschuk we can't do anything with that https://woocommerce.com/products/newsletter-subscription/, they are paid plugins, so there is no automate way of updating them.

**Comment by gtenaschuk** [comment]
Oh ok, closing this one

**Comment by mustela** [comment]
Actually, they all have a subscription key right? like a token or something, if that's in the dev site we could just update them.

**Comment by gtenaschuk** [comment]
As I know it is not by default. You have to install the plugin "WooCommerce Helper" to manage subscriptions keys.

**Comment by mustela** [comment]
Yeah it doesn't care if it is with another plugin or not, but if you have the keys on the dev site, the plugins should be updated.
