### ISSUE TITLE
Improve report message

### ISSUE THREAD

**Issue by gtenaschuk** [DinkumInteractive/mwu#52]
I would suggest to do this:
- Change the main title to: `Terminus MWU update report for: SITE_NAME`
- Remove the sentence `terminus mwu - SITE_NAME`
- Remove the sentence `pantheon site - SITE_NAME`
- Remove `Test` and `Dev` urls
- Move the screenshot at the end
- Display logs information as follow:
Dashboard               LIVE
Updates 
Log
All log information 
Updated time

Before:
<img width="652" alt="screenshot 2017-12-15 10 10 42" src="https://user-images.githubusercontent.com/368054/34048150-6ab865f2-e191-11e7-87c2-ee0a4e35ce1a.png">

After:
<img width="579" alt="screenshot 2017-12-15 10 10 42" src="https://user-images.githubusercontent.com/368054/34052021-678b447c-e19f-11e7-9337-2ef46172aff1.png">

**Comment by Sean12mps** [comment]
Roger that!
