### ISSUE TITLE
Improve messages for minor major plugin updates

### ISSUE THREAD

**Issue by gtenaschuk** [DinkumInteractive/mwu#56]
When detecting updates should be

> => Available plugin updates:
>    [ 3.3.4 ] -> [ 4.0.2 ]    akismet | Package: available `(if there is a way to avoid displaying major updates here when they are skipped, would be great)`
> => Skipped major plugin updates: To apply them, run MWU with parameter --major_update
>    [ 3.3.4 ] -> [ 4.0.2 ]    akismet

> => Plugins updated:
>    [ 3.3.4 ] -> [ 4.0.2 ]    akismet
> => No major plugin updates available.  `(Should not be displayed when running with --major_update)`

**Comment by Sean12mps** [comment]
Roger that.
