### ISSUE TITLE
Plugin version not detected correclty

### ISSUE THREAD

**Issue by gtenaschuk** [DinkumInteractive/mwu#64]
Looks like versions with 4 parts are not being detected correctly
An example `the-events-calendar | 4.6.11.1` is displayed by mwu as `[ 4.6.1 ] -> [ 4.6.1 ]    the-events-calendar | Package: available`

**Comment by Sean12mps** [comment]
Versions with more than 5 characters are trimmed actually.
So, even if it's `4.6.11`, it would be displayed as `4.6.1`.

I didn't print out the version as-is, to make sure that it'll line up nicely in the report message.
Let me think of another way to line it up nicely.

**Comment by Sean12mps** [comment]
Does it looks ok, @gtenaschuk ?

![sc](https://user-images.githubusercontent.com/7840931/36889709-c413ac8c-1e2d-11e8-98b5-c5b12309b0fc.png)

**Comment by gtenaschuk** [comment]
Yeah i would prefer having the entire version so i'm agree with that style, and maybe the blank line break is not necessary
